# Generated by Django 6.0.1 on 2026-02-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='category',
            field=models.CharField(choices=[('COFFEE', 'Coffee'), ('DESSERT', 'Dessert')], default='COFFEE', max_length=10),
        ),
    ]
